#!/usr/bin/zsh

spare_modifier="Hyper_L"
xmodmap -e "keycode 23 = $spare_modifier"
xmodmap -e "remove mod4 = $spare_modifier"
xmodmap -e "keycode any = Tab"
xcape -e "$spare_modifier=Tab"

# spare_modifier2="Hyper_R"
# xmodmap -e "keycode 51 = $spare_modifier2"
# xmodmap -e "remove mod4 = $spare_modifier2"
# xmodmap -e "keycode any = backslash"
# xcape -e "$spare_modifier2=backslash"
